"""Type stubs for the PyO3 native extension module.

These signatures are hand-maintained from ``src/bindings.rs``; CI runs an
import-time conformance check (see ``virtual_parquet`` package init) that
asserts every method/attribute declared here exists on the live extension and
vice versa. If the build fails on stub drift, update both ``src/bindings.rs``
and this file together. The native module is internal.
"""

from __future__ import annotations

from types import TracebackType
from typing import Any

class VirtualFile:
    def __init__(self, adapter: Any) -> None: ...
    def size(self) -> int: ...
    def tell(self) -> int: ...
    def seek(self, offset: int, whence: int) -> int: ...
    def read(self, n: int = -1) -> bytes: ...
    def seekable(self) -> bool: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def __enter__(self) -> VirtualFile: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...

class VirtualParquetError(Exception): ...
class SchemaMismatchError(VirtualParquetError): ...
class StatisticsMismatchError(VirtualParquetError): ...
class ByteSizeMismatchError(VirtualParquetError): ...
class NonReplayableAdapterError(VirtualParquetError): ...
