"""Type stubs for the PyO3 native extension module.

These signatures must stay in sync with ``src/bindings.rs``. The native module is
internal — see ``contracts/public-api.md``.
"""

from __future__ import annotations

from types import TracebackType
from typing import Any

class VirtualFile:
    def __init__(self, adapter: Any) -> None: ...
    def size(self) -> int: ...
    def tell(self) -> int: ...
    def seek(self, offset: int, whence: int) -> int: ...
    def read(self, n: int = -1) -> bytes: ...
    def seekable(self) -> bool: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def __enter__(self) -> VirtualFile: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None: ...

class VirtualParquetError(Exception): ...
class SchemaMismatchError(VirtualParquetError): ...
class StatisticsMismatchError(VirtualParquetError): ...
class ByteSizeMismatchError(VirtualParquetError): ...
class NonReplayableAdapterError(VirtualParquetError): ...
